# IRCBot config example
---
:server: irc.freenode.net
:port: 6667
:serverpass:
:username: bot
:nickname: bot
:realname: Bot
:userpass:
:channels:
- "#channel_one"
- "#channel_two"
:datadirectory: "~/.ircbot"
:plugins:
- :Help
- :Clock
- :Example:
    :foo: baz
    :bar: qux
- :Loader
- :Translate
- :Mnemonic
- :NumberSpell
- :Language
#- :EDICT     # EDICT and KANJIDIC need dictionary files that are not distributed
#- :KANJIDIC  # with this project. See the plugin directories for more information.
- :Converter
- :Karma
- :LP
- :Statistics
- :Tell
- :Seen
- :Dice
- :Git
