# IRCBot config example
---
:server: irc.freenode.net
:port: 6667
:serverpass:
:username: bot
:nickname: bot
:realname: Bot
:userpass:
:channels:
- "#channel_one"
- "#channel_two"
:plugins:
- :Help
- :Clock
- :Example
- :Loader
- :Translate
- :Mnemonic
- :NumberSpell
- :Language
- :Converter
