# IRCBot config example
---
:server: irc.freenode.net
:port: 6667
:serverpass:
:username: bot
:nickname: bot
:realname: Bot
:userpass:
:channels:
- "#channel_one"
- "#channel_two"
:filter:
  :LP:
    :private: false
    :otherwise: false
    "##japanese": true
:plugins:
- :Help
- :StorageYAML:
    :'data_directory': "~/.ircbot"
- :UserPool
- :ChannelPool
- :Clock
- :Example:
    :foo: baz
    :bar: qux
- :Loader
- :Translate
- :Mnemonic
- :NumberSpell
- :Language
#- :EDICT     # EDICT, KANJIDIC and Daijirin need dictionary files that are not distributed
#- :KANJIDIC  # with this project. See the plugin directories for more information.
#- :Daijirin
#- :Menu
- :Mecab
- :Converter
- :Karma
- :LP
- :Statistics
- :Tell
- :Seen
- :Dice
- :Git
- :Dotdotdot
- :Happy
- :Hello:
    "##japanese": true
- :Manage
- :Algorithms
- :URL
- :Unicode
- :WolframAlpha:
    :id: "<api-id-here>"
